### ISSUE TITLE
compilation failure - undefined: prometheus.LabelPairSorter

### ISSUE THREAD

**Issue by 26fe** [free/sql_exporter#20]
I have tried to compile a database_exporter but I got a compilation error:

```
# go get github.com/Corundex/database_exporter
# cd go/src/github.com/Corundex/database_exporter/
# go build
# github.com/Corundex/database_exporter/exporter
go/src/github.com/Corundex/database_exporter/exporter/metric.go:232:12: undefined: prometheus.LabelPairSorter
go/src/github.com/Corundex/database_exporter/exporter/target.go:67:12: undefined: prometheus.LabelPairSorter

**Comment by free** [comment]
Sorry for taking so long to answer but I have a couple of hints that may help you track down the issue:

1. You're getting this error from a fork of SQL Exporter, so it may be that the respective fork broke it.
2. You should use `go get` to check out the repository, so the Go compiler knows where to look for the code and its dependencies.
3. That being said, the `prometheus` dependency is "vendored", i.e. a snapshot of it [exists within this repository](https://github.com/free/sql_exporter/tree/master/vendor/github.com/prometheus/client_golang/prometheus) and if you have a version of Go that was released within the last couple of years, it should use that rather than grab the dependencies from elsewhere.
