### ISSUE TITLE
If two metrics use the same query_ref, is the queries results cached or is the query run twice?

### ISSUE THREAD

**Issue by invokermain** [free/sql_exporter#34]
When translating query result sets into prometheus metrics it can be useful to turn 1 result set into many metrics, this means that the same query will be called many times via query_ref.

Is a cached result set used for the query or is it run once for each metric that calls it (no clear in docs sorry)?

**Comment by free** [comment]
Each query is run exactly once per scrape and its results populate all metrics that refer to it. Because every metric is only sourced from a single query, there is no need to cache the query results: as soon as the query is run, its output is "streamed" into the relevant metrics.

If a non-zero `min_interval` is set for a collector, then the metrics themselves are cached, not the query results.
