### ISSUE TITLE
The executed interval is sometimes 30s and sometimes a minute when I have set "min_interval: 30s"

### ISSUE THREAD

**Issue by lwlei** [free/sql_exporter#83]

**Comment by lwlei** [comment]
I have set "min_interval: 30s" in "./sql_exporter.yml". However, the executed interval is sometimes 30s and sometimes a minute which can be seen from the log. I have also tried to set "min_interval: 0s" and got the same result. The last screenshot is setting of prometheus.
![image](https://user-images.githubusercontent.com/49778699/100723739-1f4fd480-33fd-11eb-9e15-6bb6196503cd.png)
![image](https://user-images.githubusercontent.com/49778699/100723876-3e4e6680-33fd-11eb-97fa-3a5d1ebd8983.png)
![image](https://user-images.githubusercontent.com/49778699/100724577-fbd95980-33fd-11eb-9c77-c240e3cecd4e.png)

**Comment by free** [comment]
That is not how `min_interval` works. It defines the minimum interval between successive DB scrapes, so that if e.g. you have multiple Prometheus instances scraping the same S!L Exporter and the queries are expensive you don't end up putting too much load on the DB. (E.g. it may (or may not) be reasonable to run a query like `select count(*) from my_table` every 30 seconds, but not every second (if you either have multiple Prometheus instances or your scrape interval is set to a few seconds.)

If you set it to 30 seconds and Prometheus is configured to scrape SQL Exporter every 30 seconds, it will sometimes scrape 29.95 seconds after the last scrape and sometimes 30.02 seconds after. In the former case, because you set `min_interval` to 30 seconds SQL Exporter will return the cached results from the previous scrape.

Either leave `min_interval` on its default (0 seconds, query the DB on every Prometheus scrape) or set it to something below 30 seconds if you're running heavy queries and actually want to run those queries at least every 30 seconds.
